### ISSUE TITLE
Fails on big-endian processor (microblaze)

### ISSUE THREAD

**Issue by gunslnger** [noporpoise/BitArray#8]
If I add 8 bytes to a bit array:
55 31 5A 12 02 31 C3 1E
And then print the bit array's words[0] with printf( "%016" PRIx64"", val ):
1ec33102125a3155
And then I loop through the bits with:
  for ( int idx = 0; idx < 64; idx++ )
  {
    if ( bit_array_get_bit( ba, idx ) == 0 )
      printf( "0" );
    else
      printf( "1" );
  }
then I get (I added spaces to make it easier to see):
10101010 10001100 01011010 01001000 01000000 10001100 11000011 01111000
Which is wrong for a big-endian processor.  It should be:
01010101 00110001 01011010 00010010 00000010 00110001 11000011 00011110
You can see that the order of the bits within each byte is backwards.  You're assuming little-endian ordering.

**Comment by gunslnger** [comment]
I have a fix for big endian, if you want it.

**Comment by noporpoise** [comment]
How are you adding bytes to the array? If you're just copying memory into the `BIT_ARRAY` `words` field this is expected behaviour. 

Do the tests all pass? Run them with `make test`

**Comment by gunslnger** [comment]
I create the bit array like this:

    ```
my_func( uint8_t * buffer )
{
    BIT_ARRAY * bit_tag = bit_array_create( BUF_SIZE * 8 );

    for ( int idx = 0; idx < BUF_SIZE; idx++ )
    {
        bit_array_set_word8( bit_tag, idx * 8, buffer[idx] );
    }
...
```

**Comment by gunslnger** [comment]
[bit_array_be.txt](https://github.com/noporpoise/BitArray/files/137348/bit_array_be.txt)
This is what I had to add to have it work correctly on a big-endian processor.

**Comment by noporpoise** [comment]
I just realised what the issue is! I think your test is wrong, not bit_array. Big endian machines reverse the order of the bytes when representing integers. They do not reverse the order of the bits. 

If we set the bytes like so:

    #define NBYTES 8
    uint8_t buffer[NBYTES] = {0x55,0x31,0x5A,0x12,0x02,0x31,0xC3,0x1E};
    for(idx = 0; idx < NBYTES; idx++)
      bit_array_set_word8(arr, idx*8, buffer[i]);

The bits of the array should now be (0..63):

    10101010 10001100 01011010 01001000 01000000 10001100 11000011 01111000
    0x55     0x31     ...
e.g. `bit_array_get(arr,0) == 1`, `bit_array_get(arr,1) == 0`, ...

This will be true for big and little endian machines. I've added a test for this, check it by running `make test`.

To explain what is going on, when you call `bit_array_set_word8(arr, 8, 0x31)`, `0x31 = 0b00110001`, bit `8` gets the least significant bit of `0x31` (`1`), bit `15` gets the most significant bit of `0x31` (`0`).
